#!/bin/zsh

# Profile file. Runs on login. Environmental variables are set here.

# Adds `~/.local/bin` to $PATH
export PATH="$PATH:$HOME/.local/bin"

# Default programs:
export EDITOR="nvim"
export BROWSER="firefox"

# Man:
export MANPAGER="nvim +Man!"

# ZSH:
export HISTSIZE=10000000
export SAVEHIST=10000000

# ~/ Clean-up:
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/zsh/history"
export NODE_REPL_HISTORY="${XDG_DATA_HOME:-$HOME/.local/share}/node/history"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export RUSTUP_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/rustup"
export PYTHONSTARTUP="${XDG_CONFIG_HOME:-$HOME/.config}/python/pythonstartup"
export PIP_TARGET="${XDG_DATA_HOME:-$HOME/.local/share}/pip"
export _Z_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/z/z"
export PKG_CACHE_PATH="${XDG_CACHE_HOME:-$HOME/.cache}/pkg"
export LESSHISTFILE="-"
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
export GRADLE_USER_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/gradle"
export VIMINIT='let $MYVIMRC = !has("nvim") ? "$XDG_CONFIG_HOME/vim/vimrc" : "$XDG_CONFIG_HOME/nvim/init.lua" | so $MYVIMRC'
export WAKATIME_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/wakatime"
export PNPM_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/pnpm"
export SQLITE_HISTORY="${XDG_DATA_HOME:-$HOME/.local/share}/sqlite_history"
export GTK2_RC_FILES="${XDG_DATA_HOME:-$HOME/.local/share}/gtk-2.0/gtkrc":"${XDG_DATA_HOME:-$HOME/.local/share}/gtk-2.0/gtkrc.mine"
export CUDA_CACHE_PATH="${XDG_CACHE_HOME:-$HOME/.cache}/nv"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export GOPATH="$XDG_DATA_HOME"/go
export GOMODCACHE="$XDG_CACHE_HOME"/go/mod

# Initialize enviroments
command -v fnm &&
export PATH="${XDG_DATA_HOME:-$HOME/.local/share}/fnm:$PATH" &&
eval "$(fnm env --use-on-cd)"
export PATH="$PNPM_HOME:$PATH"
export PATH="${XDG_DATA_HOME:-$HOME/.local/share}/npm/bin:$PATH"
eval "$(luarocks path)"
# export PATH="${XDG_DATA_HOME:-$HOME/.local/share}/pnpm:$PATH"

export PATH="$XDG_DATA_HOME/go/bin:$PATH"

# dark mode
export GTK_THEME=Adwaita:dark
export GTK2_RC_FILES=/usr/share/themes/Adwaita-dark/gtk-2.0/gtkrc
export QT_STYLE_OVERRIDE=Adwaita-Dark

# zsh-vi-mode config
export ZVM_CURSOR_STYLE_ENABLED=false

# zsh builtins help
export HELPDIR='/usr/share/zsh/5.8/help'

# less config. enable mouse and enable escape sequences
export LESS="--mouse --wheel-lines=3 -R"
